[package]
name = "chaos"
version = "0.1.0"
authors = ["Will Beason <willbeason@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
image = "0.23.14"
rand = "0.8.3"